apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio
  namespace: vamsi  
  labels:
    app: doe_socketio
spec:
  selector:
    matchLabels:
      app: doe_socketio
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: doe_socketio
    spec:
      containers:
      - name: socketio
        image: doeapp.azurecr.io/notification:152
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: socketio
  namespace: vamsi
  labels:
    app: doe_socketio
spec:
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: socketio
  selector:
    app: doe_socketio
  type: ClusterIP

